### ISSUE TITLE
No connection possible between Toon and App

### ISSUE THREAD

**Issue by Knuupke** [Inversion-NL/Toon-Android#57] opened 2021-08-05 17:39 UTC
I can't make a connection between Toon and the Android app. Settings are like always. Last update, flushed firewall rules

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App version (please complete the following information):**
 - App version [e.g. 1.0.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 3XL]
 - Android Version: [e.g. 9.0]

**Additional context or information**
Add any other context or information about the problem here.

**Comment by RoadXY** [comment] 2021-08-16 09:35
Could you fill in the form so I can debug further?
Could you try the steps outlined here:
https://www.inversion.nl/hobbies/android-applications/toon-for-android/support-voor-toon-for-android/

**Comment by Knuupke** [comment] 2021-08-16 11:21
Hi Robin,

Firewall settings flushed
Factory Reset
Gui reset

Nog steeds geen connectie met Toon
Ik weet t echt niet meer

Groet Roy

Op ma 16 aug. 2021 11:35 schreef Robin van Kekem ***@***.***>:

**Comment by RoadXY** [comment] 2021-08-16 12:39
Closing as duplicate of #59

**Closed as completed by RoadXY** 2021-08-16 12:39 UTC
Labels: bug, duplicate
