### ISSUE TITLE
No connection android and Toon

### ISSUE THREAD

**Issue by Knuupke** [Inversion-NL/Toon-Android#58] opened 2021-08-16 11:16 UTC
Flushed Firewall rules, still no connection
Factory reset, still no connection

Slowly getting crazy

*Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App version (please complete the following information):**
 - App version [e.g. 1.0.0]

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 3XL]
 - Android Version: [e.g. 9.0]

**Additional context or information**
Add any other context or information about the problem here.

**Comment by RoadXY** [comment] 2021-08-16 12:38
Closing as duplicate of #57

**Closed as completed by RoadXY** 2021-08-16 12:38 UTC
Labels: bug, duplicate
