### ISSUE TITLE
Version 0.7.1 works after clean install. Going to settings kills the app

### ISSUE THREAD

**Issue by mvdroest** [Inversion-NL/Toon-Android#51] opened 2020-10-19 14:44 UTC
On a clean install with the inital screen shown you can succesfully connect to your toon. 
As soon as you go to settings the connection is dropped and the app shows java errors (in advanced) or just shows the spinner. As soon as you go to settings it kills the app

**Comment by 1mfaasj** [comment] 2020-12-31 09:15
Indeed, i have the same problem on my android device (galaxy s10)

**Comment by RoadXY** [comment] 2021-01-26 10:56
There is a fix in 0.7.2 which will be in testing soon.

This is a duplicate of https://github.com/Inversion-NL/Toon-Android/issues/49
Please continue there.

**Closed as completed** 2021-01-26 10:56 UTC
Labels: bug, duplicate
